name: Laravel schedule monitor CI

on: [ pull_request, workflow_dispatch ]

jobs:
  php-tests:
    name: Suite (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system:
          - ubuntu-latest
        php: [ 8.1, 8.2, 8.3 ]
        laravel: [ ^9.0, ^10.0, ^11.0 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: ^9.0
            testbench: ^7.0
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
        exclude:
          - php: 8.1
            laravel: ^11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest

      - name: Execute static analysis via phpstan
        run: |
          composer test:analyze

      - name: Execute tests via phpunit
        run: |
          composer test:no-coverage

      - name: Check code style
        run: |
          composer lint:check
